### ISSUE TITLE
Server crash relating to LuckPerms

### ISSUE THREAD

**Issue by FreezyJackalope** [TheCBProject/ChickenASM#1]
I'm not sure how to describe this... The mod(s) work perfectly fine without LuckPerms, but whenever LP is installed, everything breaks. Multipart CBE and ChickenASM both seem to be causing the crash, as LuckPerms loads perfectly fine. Here's a link to the pastebin with the console log: https://paste.lucko.me/rux44e3ko3

**Comment by covers1624** [comment]
This is not a bug in ChickenASM or any of my code. I am reading a list from forge, someone else is modifying that list whilst I'm still reading it.

Unfortunately, there is nothing I can do about it.
